import dotenv from "dotenv";

dotenv.config();

const { 
  PORT, 
  DATABASE_URI, 
  GOOGLE_CLIENT_ID, 
  GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET,
  TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET,
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL
} = process.env;

export const _config = {
  PORT: PORT || 3000,
  DATABASE_URI,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET,
  TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET,
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: BETTER_AUTH_URL || "http://localhost:3000"
}; 